name: Windows Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create file from secret
        run: |
          echo "${{ secrets.PUBLIC_KEY_MALLA }}" > composeApp/src/commonMain/composeResources/files/rsa_public_mlls.pem

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew packageMsi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: general-health-tools-0.0.1
          path: composeApp/build/compose/binaries/main/msi/